:device: /dev/ttyUSB0
:status_channel: 1
:ppp_channel: 2

:poll_interval: 2      # in seconds
:balance_interval: 300 # in poll_interval's
# :balance_ussd: '*100#',

:ppp_helper: bin/ppp_helper
:apn: "internet"

